################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_calibration.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_core.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_ranging.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_strings.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_platform_log.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_tof.c 

OBJS += \
./Application/User/Core/vl53l0x/vl53l0x_api.o \
./Application/User/Core/vl53l0x/vl53l0x_api_calibration.o \
./Application/User/Core/vl53l0x/vl53l0x_api_core.o \
./Application/User/Core/vl53l0x/vl53l0x_api_ranging.o \
./Application/User/Core/vl53l0x/vl53l0x_api_strings.o \
./Application/User/Core/vl53l0x/vl53l0x_platform_log.o \
./Application/User/Core/vl53l0x/vl53l0x_tof.o 

C_DEPS += \
./Application/User/Core/vl53l0x/vl53l0x_api.d \
./Application/User/Core/vl53l0x/vl53l0x_api_calibration.d \
./Application/User/Core/vl53l0x/vl53l0x_api_core.d \
./Application/User/Core/vl53l0x/vl53l0x_api_ranging.d \
./Application/User/Core/vl53l0x/vl53l0x_api_strings.d \
./Application/User/Core/vl53l0x/vl53l0x_platform_log.d \
./Application/User/Core/vl53l0x/vl53l0x_tof.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/vl53l0x/vl53l0x_api.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_api_calibration.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_calibration.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_api_core.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_core.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_api_ranging.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_ranging.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_api_strings.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_api_strings.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_platform_log.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_platform_log.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/Core/vl53l0x/vl53l0x_tof.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/Core/Src/vl53l0x/vl53l0x_tof.c Application/User/Core/vl53l0x/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core-2f-vl53l0x

clean-Application-2f-User-2f-Core-2f-vl53l0x:
	-$(RM) ./Application/User/Core/vl53l0x/vl53l0x_api.cyclo ./Application/User/Core/vl53l0x/vl53l0x_api.d ./Application/User/Core/vl53l0x/vl53l0x_api.o ./Application/User/Core/vl53l0x/vl53l0x_api.su ./Application/User/Core/vl53l0x/vl53l0x_api_calibration.cyclo ./Application/User/Core/vl53l0x/vl53l0x_api_calibration.d ./Application/User/Core/vl53l0x/vl53l0x_api_calibration.o ./Application/User/Core/vl53l0x/vl53l0x_api_calibration.su ./Application/User/Core/vl53l0x/vl53l0x_api_core.cyclo ./Application/User/Core/vl53l0x/vl53l0x_api_core.d ./Application/User/Core/vl53l0x/vl53l0x_api_core.o ./Application/User/Core/vl53l0x/vl53l0x_api_core.su ./Application/User/Core/vl53l0x/vl53l0x_api_ranging.cyclo ./Application/User/Core/vl53l0x/vl53l0x_api_ranging.d ./Application/User/Core/vl53l0x/vl53l0x_api_ranging.o ./Application/User/Core/vl53l0x/vl53l0x_api_ranging.su ./Application/User/Core/vl53l0x/vl53l0x_api_strings.cyclo ./Application/User/Core/vl53l0x/vl53l0x_api_strings.d ./Application/User/Core/vl53l0x/vl53l0x_api_strings.o ./Application/User/Core/vl53l0x/vl53l0x_api_strings.su ./Application/User/Core/vl53l0x/vl53l0x_platform_log.cyclo ./Application/User/Core/vl53l0x/vl53l0x_platform_log.d ./Application/User/Core/vl53l0x/vl53l0x_platform_log.o ./Application/User/Core/vl53l0x/vl53l0x_platform_log.su ./Application/User/Core/vl53l0x/vl53l0x_tof.cyclo ./Application/User/Core/vl53l0x/vl53l0x_tof.d ./Application/User/Core/vl53l0x/vl53l0x_tof.o ./Application/User/Core/vl53l0x/vl53l0x_tof.su

.PHONY: clean-Application-2f-User-2f-Core-2f-vl53l0x

