################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/MotionFX_Manager.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/app_ble.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/env_server_app.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motenv_server_app.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motion_server_app.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motionfx_server_app.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/p2p_server_app.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/p2p_stm_demo.c \
/media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/wb5m_sensor_stm.c 

OBJS += \
./Application/User/STM32_WPAN/App/MotionFX_Manager.o \
./Application/User/STM32_WPAN/App/app_ble.o \
./Application/User/STM32_WPAN/App/env_server_app.o \
./Application/User/STM32_WPAN/App/motenv_server_app.o \
./Application/User/STM32_WPAN/App/motion_server_app.o \
./Application/User/STM32_WPAN/App/motionfx_server_app.o \
./Application/User/STM32_WPAN/App/p2p_server_app.o \
./Application/User/STM32_WPAN/App/p2p_stm_demo.o \
./Application/User/STM32_WPAN/App/wb5m_sensor_stm.o 

C_DEPS += \
./Application/User/STM32_WPAN/App/MotionFX_Manager.d \
./Application/User/STM32_WPAN/App/app_ble.d \
./Application/User/STM32_WPAN/App/env_server_app.d \
./Application/User/STM32_WPAN/App/motenv_server_app.d \
./Application/User/STM32_WPAN/App/motion_server_app.d \
./Application/User/STM32_WPAN/App/motionfx_server_app.d \
./Application/User/STM32_WPAN/App/p2p_server_app.d \
./Application/User/STM32_WPAN/App/p2p_stm_demo.d \
./Application/User/STM32_WPAN/App/wb5m_sensor_stm.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/STM32_WPAN/App/MotionFX_Manager.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/MotionFX_Manager.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/app_ble.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/app_ble.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/env_server_app.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/env_server_app.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/motenv_server_app.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motenv_server_app.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/motion_server_app.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motion_server_app.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/motionfx_server_app.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/motionfx_server_app.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/p2p_server_app.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/p2p_server_app.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/p2p_stm_demo.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/p2p_stm_demo.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Application/User/STM32_WPAN/App/wb5m_sensor_stm.o: /media/guerwood/Data/Dev/_linux/GitHub/Elektor_Demo_Clim/Sources/MCU/STM32WB_multiplelinks/Projects/STM32WB5MM-DK/Applications/BLE/BLE_Sensor_MotionFX/STM32_WPAN/App/wb5m_sensor_stm.c Application/User/STM32_WPAN/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DUSE_STM32WB5M_DK -DSTM32WB5Mxx -DUSE_HAL_DRIVER -c -I../../Core/Inc -I../../STM32_WPAN/App -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Utilities/sequencer -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/BSP/STM32WB5MM-DK -I../../../../../../../Drivers/BSP/Components/ssd1315 -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/LCD -I../../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../../Drivers/CMSIS/DSP/Source/FilteringFunctions -I../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Middlewares/ST/STM32_MotionFX_Library/Inc -I../../Core/Src/vl53l0x -I../../../../../../../Drivers/BSP/blinkt -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"

clean: clean-Application-2f-User-2f-STM32_WPAN-2f-App

clean-Application-2f-User-2f-STM32_WPAN-2f-App:
	-$(RM) ./Application/User/STM32_WPAN/App/MotionFX_Manager.cyclo ./Application/User/STM32_WPAN/App/MotionFX_Manager.d ./Application/User/STM32_WPAN/App/MotionFX_Manager.o ./Application/User/STM32_WPAN/App/MotionFX_Manager.su ./Application/User/STM32_WPAN/App/app_ble.cyclo ./Application/User/STM32_WPAN/App/app_ble.d ./Application/User/STM32_WPAN/App/app_ble.o ./Application/User/STM32_WPAN/App/app_ble.su ./Application/User/STM32_WPAN/App/env_server_app.cyclo ./Application/User/STM32_WPAN/App/env_server_app.d ./Application/User/STM32_WPAN/App/env_server_app.o ./Application/User/STM32_WPAN/App/env_server_app.su ./Application/User/STM32_WPAN/App/motenv_server_app.cyclo ./Application/User/STM32_WPAN/App/motenv_server_app.d ./Application/User/STM32_WPAN/App/motenv_server_app.o ./Application/User/STM32_WPAN/App/motenv_server_app.su ./Application/User/STM32_WPAN/App/motion_server_app.cyclo ./Application/User/STM32_WPAN/App/motion_server_app.d ./Application/User/STM32_WPAN/App/motion_server_app.o ./Application/User/STM32_WPAN/App/motion_server_app.su ./Application/User/STM32_WPAN/App/motionfx_server_app.cyclo ./Application/User/STM32_WPAN/App/motionfx_server_app.d ./Application/User/STM32_WPAN/App/motionfx_server_app.o ./Application/User/STM32_WPAN/App/motionfx_server_app.su ./Application/User/STM32_WPAN/App/p2p_server_app.cyclo ./Application/User/STM32_WPAN/App/p2p_server_app.d ./Application/User/STM32_WPAN/App/p2p_server_app.o ./Application/User/STM32_WPAN/App/p2p_server_app.su ./Application/User/STM32_WPAN/App/p2p_stm_demo.cyclo ./Application/User/STM32_WPAN/App/p2p_stm_demo.d ./Application/User/STM32_WPAN/App/p2p_stm_demo.o ./Application/User/STM32_WPAN/App/p2p_stm_demo.su ./Application/User/STM32_WPAN/App/wb5m_sensor_stm.cyclo ./Application/User/STM32_WPAN/App/wb5m_sensor_stm.d ./Application/User/STM32_WPAN/App/wb5m_sensor_stm.o ./Application/User/STM32_WPAN/App/wb5m_sensor_stm.su

.PHONY: clean-Application-2f-User-2f-STM32_WPAN-2f-App

